### ISSUE TITLE
trusted_users  vs trusted_chats

### ISSUE THREAD

**Issue by ittech25** [Suburbanno/SWRATT#1]
Hi @Suburbanno 
Sorry for not good english. I'm Newbie python
What is different trusted_users & trusted_chats  ?
I want sent to multiple Trusted Users but notwoking
trusted_users = [xxxxxxxx,xxxxxxxxx]
Error :
 ('Bad Request: chat not found'
Test invidual Trusted user working fine

**Comment by Suburbanno** [comment]
@ittech25 hey!
trusted_users = [ ] - Trusted users who can communicate with the bot (id)
trusted_chats = [ ] - Trusted groups (id)

**Comment by ittech25** [comment]
Thank you @Suburbanno 
trusted_users = [ID1 , ID2] is not working. How can fix it ?

**Comment by Suburbanno** [comment]
I'll check, did you try this?

trusted_users = [968540009, 678557800]
trusted_chats = [-968540009, -678557800]

**Comment by ittech25** [comment]
Yes, i'm tried
trusted_users = [MyID1, MyID2]
trusted_chats = [-968540009]
Error ==> Forbidden: bot can't initiate conversation with a user

**Comment by Suburbanno** [comment]
u bot within the group? for me it works...
![image](https://user-images.githubusercontent.com/13632826/83012653-12879980-9ff2-11ea-81b8-b6b6a83ce97f.png)

**Comment by ittech25** [comment]
Thanks @Suburbanno 
trusted_users = [MyID1] ==> Working
trusted_users = [MyID1, MyID2] ==> Not Working

**Comment by Suburbanno** [comment]
the API is out of date, I didn't find a solution, so you can only use a private or group conversation with everyone having access to the bot....

ex:
trusted_users = []
trusted_chats = [-99999999 ] all group members have access to use bot

trusted_users = [99999999] u private chat
trusted_chats = []

**Comment by ittech25** [comment]
Thank you @Suburbanno
