### ISSUE TITLE
" HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot"

### ISSUE THREAD

**Issue by Randummm** [Suburbanno/SWRATT#3]
![Knipsel](https://user-images.githubusercontent.com/65246020/83326647-03188280-a276-11ea-9676-ee7803e451f0.PNG)
I've only executed the script once so im not sure why its giving me rate limit errors.

**Comment by Suburbanno** [comment]
Are you using proxy or something? try to install the dependencies again.

working fine for me
![image](https://user-images.githubusercontent.com/13632826/83329297-0a806180-a25f-11ea-97a2-184c56c06e8b.png)
