### ISSUE TITLE
Several connections

### ISSUE THREAD

**Issue by IamKO** [Suburbanno/SWRATT#5]
Hello, can rat execute a command in cmd without showing cmd window? plus rat can handle several slaves or only one? and connection will be alive until the computer will be turned off or it has some limits, for example, will be turned off after 1 hour of inactivity?

**Comment by Suburbanno** [comment]
> can rat execute a command in cmd without showing cmd window?
- nop
> plus rat can handle several slaves or only one?
- just one
> and connection will be alive until the computer will be turned off or it has some limits
- the connection is lost at the same time the computer is turned off
